version: '2'
 
services:

  web:
    container_name: flaskweb
    build: ./web
    # ports:
    #   - "8000:8000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    volumes:
     - ./web:/usr/src/app/web
      # - data-volume:/usr/src/app/web
    command: flask run --host=0.0.0.0 --port=8000
    depends_on:
      - db

  nginx:
    container_name: nginxproxy
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
      # - data-volume:/usr/src/app/web
    # volumes_from:
    #   - web
    depends_on:
      - web

  db:
    container_name: mongodock
    image: mongo:3.4.9
    volumes:
      - .mongodb/db_data/data/db/:/data/db
    # ports:
    #   - "27017:27017"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    expose:
      - "27017"


# volumes:
#  data-volume:




# cd projectfolder
# ls
# cat docker-compose.yml

# docker-compose up -d
# docker-compose down --volumes 

